import { Show } from "@/types/show";
import { Product } from "@/types/merch";
import { Video } from "@/types/video";

export const mockShows: Show[] = [
  {
    id: "1",
    title: "William Montgomery Live",
    venue: "The Comedy Mothership",
    city: "Austin",
    state: "TX",
    country: "US",
    date: "2026-03-22T20:00:00-06:00",
    doors_time: "19:00",
    show_time: "20:00",
    ticket_url: "https://thecomedymothership.com",
    ticket_price: 35.0,
    status: "upcoming",
    image_url: null,
    notes: null,
    is_featured: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "2",
    title: "The Big Red Machine Tour",
    venue: "Zanies Nashville",
    city: "Nashville",
    state: "TN",
    country: "US",
    date: "2026-04-05T19:30:00-05:00",
    doors_time: "18:30",
    show_time: "19:30",
    ticket_url: "https://zanies.com",
    ticket_price: 30.0,
    status: "upcoming",
    image_url: null,
    notes: "Two shows!",
    is_featured: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "3",
    title: "William Montgomery Weekend",
    venue: "The Improv",
    city: "Houston",
    state: "TX",
    country: "US",
    date: "2026-04-12T20:00:00-05:00",
    doors_time: "19:00",
    show_time: "20:00",
    ticket_url: "https://improv.com/houston",
    ticket_price: 40.0,
    status: "upcoming",
    image_url: null,
    notes: null,
    is_featured: false,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "4",
    title: "Sold Out Special",
    venue: "Cap City Comedy Club",
    city: "Austin",
    state: "TX",
    country: "US",
    date: "2026-03-15T21:00:00-06:00",
    doors_time: "20:00",
    show_time: "21:00",
    ticket_url: null,
    ticket_price: 45.0,
    status: "sold_out",
    image_url: null,
    notes: "Opening for Joe Rogan",
    is_featured: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "5",
    title: "Memphis Homecoming",
    venue: "Chuckles Comedy House",
    city: "Memphis",
    state: "TN",
    country: "US",
    date: "2026-04-19T20:00:00-05:00",
    doors_time: "19:00",
    show_time: "20:00",
    ticket_url: "https://chucklescomedyhouse.com",
    ticket_price: 25.0,
    status: "upcoming",
    image_url: null,
    notes: "Hometown show!",
    is_featured: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
];

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "End An Episode Tee",
    description: "There's Only One Way To End An Episode - William Montgomery",
    price: 24.0,
    compare_at_price: null,
    images: ["/images/merch/merch-1.jpg"],
    category: "apparel",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
    in_stock: true,
    stripe_price_id: null,
    sort_order: 1,
    is_featured: true,
    url: "https://www.teepublic.com/t-shirt/53184127-theres-only-one-way-to-end-an-episode-like-this-wi",
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "2",
    name: "Cartoon William Tee",
    description: "If William Montgomery From Kill Tony Was A Cartoon",
    price: 24.0,
    compare_at_price: null,
    images: ["/images/merch/merch-2.jpg"],
    category: "apparel",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
    in_stock: true,
    stripe_price_id: null,
    sort_order: 2,
    is_featured: true,
    url: "https://www.teepublic.com/t-shirt/49354399-if-william-montgomery-from-kill-tony-was-a-cartoon",
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "3",
    name: "I Ain't Never Gonna Stop Tee",
    description: "Crazy William Montgomery - I ain't never gonna stop",
    price: 24.0,
    compare_at_price: null,
    images: ["/images/merch/merch-3.jpg"],
    category: "apparel",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
    in_stock: true,
    stripe_price_id: null,
    sort_order: 3,
    is_featured: true,
    url: "https://www.teepublic.com/t-shirt/52206308-crazy-william-montgomery-kill-tony-ill-i-aint-neve",
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "4",
    name: "The William Montgomery Show Tee",
    description: "The William Montgomery Show - official design",
    price: 24.0,
    compare_at_price: null,
    images: ["/images/merch/merch-4.jpg"],
    category: "apparel",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
    in_stock: true,
    stripe_price_id: null,
    sort_order: 4,
    is_featured: true,
    url: "https://www.teepublic.com/t-shirt/54960298-the-william-montgomery-show",
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
];

export const mockVideos: Video[] = [
  {
    id: "1",
    title: "William Montgomery - Kill Tony Best Moments",
    youtube_id: "z7JsJYWtW28",
    description: "A compilation of William's best Kill Tony one-minute sets",
    thumbnail_url: null,
    category: "kill_tony",
    duration: "12:34",
    publish_date: "2026-01-15",
    is_featured: true,
    sort_order: 1,
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "2",
    title: "The William Montgomery Show - Ep. 200",
    youtube_id: "Ez9cQg-wa1w",
    description: "Milestone episode with special guests",
    thumbnail_url: null,
    category: "podcast",
    duration: "1:23:45",
    publish_date: "2026-02-01",
    is_featured: true,
    sort_order: 2,
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "3",
    title: "William Montgomery Stand-Up Set - Comedy Mothership",
    youtube_id: "ThYO8xr2ixQ",
    description: "Full 15-minute set from The Comedy Mothership",
    thumbnail_url: null,
    category: "clip",
    duration: "15:22",
    publish_date: "2026-02-15",
    is_featured: true,
    sort_order: 3,
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "4",
    title: "The Big Red Machine - Full Special",
    youtube_id: "PjTChaFqZvQ",
    description: "William's first full-length comedy special",
    thumbnail_url: null,
    category: "special",
    duration: "45:00",
    publish_date: "2025-12-01",
    is_featured: true,
    sort_order: 0,
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "5",
    title: "Kill Tony #700 - William Montgomery Returns",
    youtube_id: "oCs-xw_TF_I",
    description: "William's legendary return to Kill Tony",
    thumbnail_url: null,
    category: "kill_tony",
    duration: "8:15",
    publish_date: "2026-03-01",
    is_featured: true,
    sort_order: 4,
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "6",
    title: "William Montgomery Interview - Rough Week Podcast",
    youtube_id: "ghDaTYbmC9o",
    description: "William talks about his early days on Kill Tony",
    thumbnail_url: null,
    category: "interview",
    duration: "55:30",
    publish_date: "2025-11-01",
    is_featured: true,
    sort_order: 5,
    created_at: "2026-01-01T00:00:00Z",
  },
];
