import { Show } from "@/types/show";
import { Product } from "@/types/merch";
import { Video } from "@/types/video";

export const mockShows: Show[] = [
  {
    id: "1",
    title: "William Montgomery Live",
    venue: "The Comedy Mothership",
    city: "Austin",
    state: "TX",
    country: "US",
    date: "2026-03-22T20:00:00-06:00",
    doors_time: "19:00",
    show_time: "20:00",
    ticket_url: "https://thecomedymothership.com",
    ticket_price: 35.0,
    status: "upcoming",
    image_url: null,
    notes: null,
    is_featured: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "2",
    title: "The Big Red Machine Tour",
    venue: "Zanies Nashville",
    city: "Nashville",
    state: "TN",
    country: "US",
    date: "2026-04-05T19:30:00-05:00",
    doors_time: "18:30",
    show_time: "19:30",
    ticket_url: "https://zanies.com",
    ticket_price: 30.0,
    status: "upcoming",
    image_url: null,
    notes: "Two shows!",
    is_featured: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "3",
    title: "William Montgomery Weekend",
    venue: "The Improv",
    city: "Houston",
    state: "TX",
    country: "US",
    date: "2026-04-12T20:00:00-05:00",
    doors_time: "19:00",
    show_time: "20:00",
    ticket_url: "https://improv.com/houston",
    ticket_price: 40.0,
    status: "upcoming",
    image_url: null,
    notes: null,
    is_featured: false,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "4",
    title: "Sold Out Special",
    venue: "Cap City Comedy Club",
    city: "Austin",
    state: "TX",
    country: "US",
    date: "2026-03-15T21:00:00-06:00",
    doors_time: "20:00",
    show_time: "21:00",
    ticket_url: null,
    ticket_price: 45.0,
    status: "sold_out",
    image_url: null,
    notes: "Opening for Joe Rogan",
    is_featured: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "5",
    title: "Memphis Homecoming",
    venue: "Chuckles Comedy House",
    city: "Memphis",
    state: "TN",
    country: "US",
    date: "2026-04-19T20:00:00-05:00",
    doors_time: "19:00",
    show_time: "20:00",
    ticket_url: "https://chucklescomedyhouse.com",
    ticket_price: 25.0,
    status: "upcoming",
    image_url: null,
    notes: "Hometown show!",
    is_featured: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
];

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Big Red Machine Tee",
    description: "Classic black tee with The Big Red Machine logo",
    price: 35.0,
    compare_at_price: null,
    images: ["/images/merch/big-red-tee.jpg"],
    category: "apparel",
    sizes: ["S", "M", "L", "XL", "2XL"],
    in_stock: true,
    stripe_price_id: null,
    sort_order: 1,
    is_featured: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "2",
    name: "Vanilla Gorilla Snapback",
    description: "Black snapback hat with embroidered Vanilla Gorilla text",
    price: 28.0,
    compare_at_price: null,
    images: ["/images/merch/vg-hat.jpg"],
    category: "accessories",
    sizes: null,
    in_stock: true,
    stripe_price_id: null,
    sort_order: 2,
    is_featured: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "3",
    name: "STAAAAAHP Hoodie",
    description:
      "Premium heavyweight hoodie - I ain't NEVER GONNA STAAAAAHP",
    price: 55.0,
    compare_at_price: 65.0,
    images: ["/images/merch/staahp-hoodie.jpg"],
    category: "apparel",
    sizes: ["S", "M", "L", "XL", "2XL"],
    in_stock: true,
    stripe_price_id: null,
    sort_order: 3,
    is_featured: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "4",
    name: "Memphis Madman Poster",
    description: "Limited edition 18x24 poster - artwork by Ryan J Ebelt",
    price: 20.0,
    compare_at_price: null,
    images: ["/images/merch/poster.jpg"],
    category: "accessories",
    sizes: null,
    in_stock: true,
    stripe_price_id: null,
    sort_order: 4,
    is_featured: false,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
];

export const mockVideos: Video[] = [
  {
    id: "1",
    title: "William Montgomery - Kill Tony Best Moments",
    youtube_id: "z7JsJYWtW28",
    description: "A compilation of William's best Kill Tony one-minute sets",
    thumbnail_url: null,
    category: "kill_tony",
    duration: "12:34",
    publish_date: "2026-01-15",
    is_featured: true,
    sort_order: 1,
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "2",
    title: "The William Montgomery Show - Ep. 200",
    youtube_id: "dQw4w9WgXcQ",
    description: "Milestone episode with special guests",
    thumbnail_url: null,
    category: "podcast",
    duration: "1:23:45",
    publish_date: "2026-02-01",
    is_featured: true,
    sort_order: 2,
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "3",
    title: "William Montgomery Stand-Up Set - Comedy Mothership",
    youtube_id: "dQw4w9WgXcQ",
    description: "Full 15-minute set from The Comedy Mothership",
    thumbnail_url: null,
    category: "clip",
    duration: "15:22",
    publish_date: "2026-02-15",
    is_featured: true,
    sort_order: 3,
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "4",
    title: "The Big Red Machine - Full Special",
    youtube_id: "PjTChaFqZvQ",
    description: "William's first full-length comedy special",
    thumbnail_url: null,
    category: "special",
    duration: "45:00",
    publish_date: "2025-12-01",
    is_featured: true,
    sort_order: 0,
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "5",
    title: "Kill Tony #700 - William Montgomery Returns",
    youtube_id: "dQw4w9WgXcQ",
    description: "William's legendary return to Kill Tony",
    thumbnail_url: null,
    category: "kill_tony",
    duration: "8:15",
    publish_date: "2026-03-01",
    is_featured: false,
    sort_order: 5,
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "6",
    title: "William Montgomery Interview - Rough Week Podcast",
    youtube_id: "dQw4w9WgXcQ",
    description: "William talks about his early days on Kill Tony",
    thumbnail_url: null,
    category: "interview",
    duration: "55:30",
    publish_date: "2025-11-01",
    is_featured: false,
    sort_order: 6,
    created_at: "2026-01-01T00:00:00Z",
  },
];
